%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\james\Documents\MATLAB\filtro_fir_completo\mpu6050.dat
%
% Auto-generated by MATLAB on 08-Oct-2020 16:20:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "AcX", "AcY", "AcZ"];
opts.SelectedVariableNames = ["AcX", "AcY", "AcZ"];
opts.VariableTypes = ["string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\james\Documents\MATLAB\filtro_fir_completo\mpu6050.dat", opts);

%% Convert to output type
AcX = tbl.AcX;
AcY = tbl.AcY;
AcZ = tbl.AcZ;

%% Clear temporary variables
clear opts tbl