/**
 * Project Classes Placa Central
 */

#ifndef _CONSTANTES_H
#define _CONSTANTES_H

#define INTERVALO_TIMER_MS 200
#define TEMPERATURA_CRITICA_CVT 200
#define RAIO_PNEU 22
#define QTD_SENSORES_PNEU 4

static const long MINUTO = 60 * (1000 / INTERVALO_TIMER_MS);
static const bool DEBUG_MODE = true;

enum Nivel
{
    BAIXO,
    MEDIO,
    ALTO
};

#define SERIAL_BAUD 115200 // SERIAL DEBUG

// TELEMETRIA SERIAL1 UART
#define TELEMETRIA_RX 1 // PINO RX UART LORA
#define TELEMETRIA_TX 0 // PINO TX UART LORA

// GPS SERIAL1 UART
#define GPS_TX 8 // PINO TX UART GPS
#define GPS_RX 9 // PINO RX UART GPS
#define GPS_BAUD 9600

// CAN SPI
#define CAN_SCKPIN 10
#define CAN_TXPIN 11 // MOSI/TX CAN
#define CAN_RXPIN 12 // MISO/RX CAN
#define CAN_CSPIN 13

// SD SPI1
#define SD_RXPIN 16 // MISO
#define SD_CSPIN 17
#define SD_SCKPIN 18
#define SD_TXPIN 19 // MOSI

// FREIO
#define NIVEL_FREIO 20
#define PRESSAO_FREIO 27

// DIVISOR TENSAO
#define DIV_TENSAO 26
#define BATERIA_TENSAO_MAX 13.3

// COMBUSTIVEL
#define COMB_INFERIOR 14
#define COMB_SUPERIOR 15

// RPM
#define RPM_INTERRUPT_PIN 21

#endif //_CONSTANTES_H