% Compute spectrogram

% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.

% Generated on: 08-Oct-2020 17:41:49
function  AcZ_ROI = spectrograma(AcZ, Fs,time)
% Parameters
k = time/1000;
n = time(end)/1000;
timeLimits = [0.01 n]; % seconds
frequencyLimits = [0 Fs]; % Hz
overlapPercent = 50;

%%
% Index into signal time region of interest
AcZ_ROI = AcZ(:);
timeValues = k;
minIdx = timeValues >= timeLimits(1);
maxIdx = timeValues <= timeLimits(2);
AcZ_ROI = AcZ_ROI(minIdx&maxIdx);
timeValues = timeValues(minIdx&maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
pspectrum(AcZ_ROI,timeValues, ...
    'spectrogram', ...
    'FrequencyLimits',frequencyLimits, ...
    'OverlapPercent',overlapPercent);
end
